### ISSUE TITLE
Testing nested components

### ISSUE THREAD

**Issue by ngerritsen** [ericelliott/react-pure-component-starter#81]
Could there be an example of testing nested pure components? I always found that hard to test without needing to know the implementation of a child component. With class-components you could select them by type.

**Comment by ericelliott** [comment]
> Could there be an example of testing nested pure components? I always found that hard to test without needing to know the implementation of a child component.

Child components should get their own set of tests -- don't repeat child-specific tests at the top level -- so testing nested pure components is just like testing un-nested pure components. Just pass in the props and check for expected output.

**Comment by ericelliott** [comment]
If you have a more specific example you'd like me to address, feel free to share. Otherwise, closing.

**Comment by ngerritsen** [comment]
I mean if you have ComponentA and it's child is ComponentB, you pass a message to B like < ComponentB message={message} />. How could you only check that the correct value is passed to ComponentB's props, without having to know what it actually does with it.

**Comment by ericelliott** [comment]
You should only unit test the public API of your modules. To do otherwise is to lock yourself into implementation details which tend to change a lot, which will wreck your productivity, and gain you nothing.

> How could you only check that the correct value is passed to ComponentB's props, without having to know what it actually does with it.

**Don't.** It sounds like you're trying to unit test React, or unit test _the internal implementation_ of ComponentA.

**IF and only IF** ComponentA exposes `message` on its own public API, you can test its value there.

Otherwise, give ComponentA some props and _make sure ComponentA renders what you expect it to render._

That is the essence of the public API of a React component. Other details like state, its children, and context are internal implementation details that should not be unit tested.

**Comment by ngerritsen** [comment]
Thanks for the elaboration!

**Comment by ericelliott** [comment]
Thanks for asking! =)
